### ISSUE TITLE
Retrieving all lines

### ISSUE THREAD

**Issue by TonyValenti** [better-reports/QuickBooksSharp#7]
What query would I use to retrieve all line items on all invoices?

**Comment by TonyValenti** [comment]
Also, how would I retrieve all unbilled expenses for all vendors?

**Comment by clement911** [comment]
This is more of a question about the query language rather than ShopifySharp itself.
You'll have to retrieve all the invoices by paginating. Each invoice object contains the lines it has.
See https://developer.intuit.com/app/developer/qbo/docs/learn/explore-the-quickbooks-online-api/data-queries for more info on how to query.
